### ISSUE TITLE
Needed for gopherclient?

### ISSUE THREAD

**Issue by vcg3rd** [prologic/go-gopher#4]
So, I use gopher still, and just installed openSUSE Tumbleweed only to find it doesn't even have the protocol, anywhere, let alone a client. Not so much as a man page.  Plus, neither Lynx nor Firefox will resolve a gopher address, so I suspect it's because there's no protocol.

I want to try https://github.com/prologic/gopherclient, but do I need to install this first?

Sorry.  This isn't really an issue, but openSUSE on irc and Reddit have been no help.

Thanks!

**Comment by prologic** [comment]
Hi @vcg3rd 

In order to build [gopherclient](https://github.com/prologic/gopherclient) you need only run its build instructions. It is written in [Go](https://golang.org) and so will pull this library in as a dependency automatically via the Go build system.

That being said; I _could_ / _should_ also start publishing binaries and make a new release of [gopherclient](https://github.com/prologic/gopherclient) -- Feel free to file an issue there to remind me to do so :)

**Comment by vcg3rd** [comment]
Thanks!  I will.
